# Generated by Django 4.2.3 on 2023-07-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0002_alter_vente_prix_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='user',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
