# Generated by Django 4.2.3 on 2023-07-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0005_vente_prix_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='utilisateur',
        ),
    ]
