# Generated by Django 4.2.3 on 2023-08-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0010_alter_produit_prix_unitaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='nom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercice.produit'),
        ),
    ]
