# Generated by Django 4.2.3 on 2023-08-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0013_alter_vente_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='prix_unitaire',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
