# Generated by Django 4.2.3 on 2023-08-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0015_alter_vente_prix_unitaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vente',
            old_name='prix_unitaire',
            new_name='prix_unique',
        ),
    ]
