# Generated by Django 4.2.3 on 2023-09-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0016_rename_prix_unitaire_vente_prix_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='nom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercice.produit'),
            preserve_default=False,
        ),
    ]
